/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject.com.dcoms.client.view;

import finalproject.com.dcoms.client.controller.EmployeeController;
import finalproject.com.dcoms.client.model.Employee;
import java.awt.Image;

/**
 *
 * @author zaku
 */
public class EmployeeFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmployeeFrame.class.getName());

    private EmployeeController controller;
    
    /**
     * Creates new form EmployeeJFrame
     */
    public EmployeeFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void setController(EmployeeController controller) {
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel = new javax.swing.JPanel();
        loadingPanel = new finalproject.com.dcoms.client.view.LoadingPanel();
        employeeDashboardPanel = new finalproject.com.dcoms.client.view.EmployeeDashboard();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        parentPanel.setLayout(new java.awt.CardLayout());
        parentPanel.add(loadingPanel, "card3");
        parentPanel.add(employeeDashboardPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmployeeFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private finalproject.com.dcoms.client.view.EmployeeDashboard employeeDashboardPanel;
    private finalproject.com.dcoms.client.view.LoadingPanel loadingPanel;
    private javax.swing.JPanel parentPanel;
    // End of variables declaration//GEN-END:variables
    
    
    
    public void setEmployeeDetails(Employee employee) {
        if (employee == null) return;
        
        employeeDashboardPanel.setTitle("Welcome back, " + employee.getFirstName());
        employeeDashboardPanel.setLeaveBalanceLabel(employee.getLeaveBalance() + " / 20");
        employeeDashboardPanel.setLeaveBalanceBar(0, 20, employee.getLeaveBalance());
        employeeDashboardPanel.setEmployeeIdLabel(String.valueOf(employee.getEmployeeId()));
        
        loadingPanel.setVisible(false);
        employeeDashboardPanel.setVisible(true);
    }
}
