/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalproject.com.dcoms.client.view;

import finalproject.com.dcoms.client.controller.StaffController;

/**
 *
 * @author ysssh
 */
public class HRRegistration extends javax.swing.JPanel {
        private StaffController controller;

        /**
         * Creates new form HRRegistration
         */
        public HRRegistration() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel(
                                new javax.swing.ImageIcon(
                                                new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))
                                                                .getImage().getScaledInstance(100, 100,
                                                                                java.awt.Image.SCALE_SMOOTH)));
                jLabel2 = new javax.swing.JLabel(
                                new javax.swing.ImageIcon(
                                                new javax.swing.ImageIcon(getClass().getResource("/images/avatar.png"))
                                                                .getImage().getScaledInstance(100, 100,
                                                                                java.awt.Image.SCALE_SMOOTH)));
                staffId = new javax.swing.JLabel();
                lblDashboard = new javax.swing.JLabel();
                lblEmpRegister = new javax.swing.JLabel();
                lblGenReport = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                titleLabel = new javax.swing.JLabel();
                lblFirstName = new javax.swing.JLabel();
                txtFirstName = new javax.swing.JTextField();
                lblLastName = new javax.swing.JLabel();
                txtLastName = new javax.swing.JTextField();
                lblPassport = new javax.swing.JLabel();
                txtPassportNumber = new javax.swing.JTextField();
                lblUsername = new javax.swing.JLabel();
                txtUsername = new javax.swing.JTextField();
                lblPassword = new javax.swing.JLabel();
                txtPassword = new javax.swing.JTextField();
                lblPassConfirm = new javax.swing.JLabel();
                txtPassConfirm = new javax.swing.JTextField();
                btnRegister = new javax.swing.JButton();

                jPanel1.setBackground(new java.awt.Color(102, 153, 255));

                jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                staffId.setForeground(new java.awt.Color(255, 255, 255));
                staffId.setText("staffId");

                lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
                lblDashboard.setText("Dashboard");
                lblDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                lblEmpRegister.setForeground(new java.awt.Color(255, 255, 255));
                lblEmpRegister.setText("Register Employees");
                lblEmpRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                lblGenReport.setForeground(new java.awt.Color(255, 255, 255));
                lblGenReport.setText("Generate Report");
                lblGenReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                lblGenReport.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblGenReportMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(14, 14, 14)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                113,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                50,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(staffId,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                84,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(27, Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(lblGenReport,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                155,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblEmpRegister,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                155,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblDashboard,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                155,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(27, 27, 27)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                113,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblDashboard)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(lblEmpRegister)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(lblGenReport)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                50,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(16, 16, 16))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                .addComponent(staffId)
                                                                                                                .addGap(34, 34, 34)))));

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));

                titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                titleLabel.setText("Register New Employee");

                lblFirstName.setText("First Name");
                lblFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14));
                txtFirstName.setPreferredSize(new java.awt.Dimension(200, 30));

                lblLastName.setText("Last Name");
                lblLastName.setFont(new java.awt.Font("Segoe UI", 0, 14));
                txtLastName.setPreferredSize(new java.awt.Dimension(200, 30));
                txtLastName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtLastNameActionPerformed(evt);
                        }
                });

                lblPassport.setText("IC/Passport Number");
                lblPassport.setFont(new java.awt.Font("Segoe UI", 0, 14));
                txtPassportNumber.setPreferredSize(new java.awt.Dimension(200, 30));

                lblUsername.setText("Username");
                lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 14));
                txtUsername.setPreferredSize(new java.awt.Dimension(200, 30));

                lblPassword.setText("Password");
                lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 14));
                txtPassword.setPreferredSize(new java.awt.Dimension(200, 30));

                lblPassConfirm.setText("Confirm Password");
                lblPassConfirm.setFont(new java.awt.Font("Segoe UI", 0, 14));
                txtPassConfirm.setPreferredSize(new java.awt.Dimension(200, 30));

                btnRegister.setText("Register");
                btnRegister.setBackground(new java.awt.Color(102, 153, 255));
                btnRegister.setForeground(new java.awt.Color(255, 255, 255));
                btnRegister.setFocusPainted(false);
                btnRegister.setPreferredSize(new java.awt.Dimension(130, 35));
                btnRegister.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRegisterActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(40, 40, 40)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(lblFirstName)
                                                                                                                .addComponent(txtFirstName,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                200,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(40, 40, 40)
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(lblLastName)
                                                                                                                .addComponent(txtLastName,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                200,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(lblPassport)
                                                                                                                .addComponent(txtPassportNumber,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                200,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(lblUsername)
                                                                                                                .addComponent(txtUsername,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                200,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(40, 40, 40)
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(lblPassword)
                                                                                                                .addComponent(txtPassword,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                200,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(lblPassConfirm)
                                                                                                                .addComponent(txtPassConfirm,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                200,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(169, 169, 169)))
                                                                .addContainerGap(40, Short.MAX_VALUE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(195, 195, 195)
                                                                .addComponent(btnRegister,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                130,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(lblFirstName)
                                                                                                .addGap(5, 5, 5)
                                                                                                .addComponent(txtFirstName,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                30,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(lblLastName)
                                                                                                .addGap(5, 5, 5)
                                                                                                .addComponent(txtLastName,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                30,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(20, 20, 20)
                                                                .addComponent(lblPassport)
                                                                .addGap(5, 5, 5)
                                                                .addComponent(txtPassportNumber,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                30,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(20, 20, 20)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(lblUsername)
                                                                                                .addGap(5, 5, 5)
                                                                                                .addComponent(txtUsername,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                30,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(lblPassword)
                                                                                                .addGap(5, 5, 5)
                                                                                                .addComponent(txtPassword,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                30,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(20, 20, 20)
                                                                .addComponent(lblPassConfirm)
                                                                .addGap(5, 5, 5)
                                                                .addComponent(txtPassConfirm,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                30,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(30, 30, 30)
                                                                .addComponent(btnRegister,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                35,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(titleLabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                550,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jPanel2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(23, 23, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(titleLabel)
                                                                .addGap(34, 34, 34)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(125, Short.MAX_VALUE)));
        }// </editor-fold>//GEN-END:initComponents

        private void lblGenReportMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblGenReportMouseClicked
                controller.openReportUI();
        }// GEN-LAST:event_lblGenReportMouseClicked

        private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtLastNameActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtLastNameActionPerformed

        private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegisterActionPerformed
                controller.registerEmp(txtFirstName.getText(), txtLastName.getText(), txtPassportNumber.getText(),
                                txtUsername.getText(), txtPassword.getText(), txtPassConfirm.getText());
        }// GEN-LAST:event_btnRegisterActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnRegister;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JLabel lblDashboard;
        private javax.swing.JLabel lblEmpRegister;
        private javax.swing.JLabel lblFirstName;
        private javax.swing.JLabel lblGenReport;
        private javax.swing.JLabel lblLastName;
        private javax.swing.JLabel lblPassConfirm;
        private javax.swing.JLabel lblPassport;
        private javax.swing.JLabel lblPassword;
        private javax.swing.JLabel lblUsername;
        private javax.swing.JLabel staffId;
        private javax.swing.JLabel titleLabel;
        private javax.swing.JTextField txtFirstName;
        private javax.swing.JTextField txtLastName;
        private javax.swing.JTextField txtPassConfirm;
        private javax.swing.JTextField txtPassportNumber;
        private javax.swing.JTextField txtPassword;
        private javax.swing.JTextField txtUsername;

        // End of variables declaration//GEN-END:variables
        public void setController(StaffController controller) {
                this.controller = controller;
        }
}